# Generated by Django 4.2.3 on 2023-07-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetails',
            name='picture',
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='account_type',
            field=models.CharField(choices=[('Savings Account', 'Savings Account'), ('Current Account', 'Current Account'), ('Checking Account', 'Checking Account'), ('Fixed Deposit Account', 'Fixed Deposit Account'), ('Crypto Currency Account', 'Crypto Currency Account'), ('Business Account', 'Business Account'), ('Non Resident Account', 'Non Resident Account'), ('Cooperate Business Account', 'Cooperate Business Account'), ('Investment Account', 'Investment Account')], max_length=30),
        ),
    ]
