# Generated by Django 4.2.3 on 2023-07-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_accountdetails_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetails',
            name='status',
            field=models.CharField(choices=[('VERIFIED', 'VERIFIED'), ('UNVERIFIED', 'UNVERIFIED')], default='PENDING', max_length=20),
        ),
    ]
