# Generated by Django 4.2.3 on 2023-07-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountdetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='status',
            field=models.CharField(choices=[('VERIFIED', 'VERIFIED'), ('UNVERIFIED', 'UNVERIFIED'), ('PENDING', 'PENDING')], default='PENDING', max_length=20),
        ),
    ]
