# Generated by Django 4.2.1 on 2023-07-27 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accountdetails_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountdetails',
            name='picture',
            field=models.FileField(blank=True, default='qww.png', null=True, upload_to='account_pictures/'),
        ),
    ]
