# Generated by Django 4.2.3 on 2023-08-19 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_accountdetails_id_alter_loginhistory_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountdetails',
            name='picture',
        ),
    ]
