# Generated by Django 4.2.3 on 2023-07-23 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='proof_of_pay',
        ),
    ]
